- index.html
> Fix IRC channel on main page

- index.html
- media.html
> adds #devbus to the website officially, restores #coderbus

- index.html
- media.html
* Removed "Github" from Navbar
* Added "Development" Dropdown to Navbar:
* /tg/ Github Link
* /tg/station13 Website Github Link
* Declaration Finder tool (findshit.php) Link
* Made some of MSO's local changes official to the site (pls mso if it becomes a long standing change (like /tg/station outcasts) pls update it officially)
> Site Update 10/03/2016 - Development Dropdown

- index.html
- media.html
wow it is so weird that I don't have to write 2 paragraphs about why this would be a good and balanced change
> Adds xenobio guide to the list

- tgdb/irvpolltally.php
- tgdb/templates/ipv.tpl
Also fixed bug causing poll list to show not yet started polls.
> Adds admin only option to poll filtering

- tgdb/playerdetails.php
Keeps the consistency with everything else
> Changes the note query to be  DESC instead of ascendent

- tgdb/bandetails.php
- tgdb/templates/bandetails.tpl
Also fixes server ip not displaying correctly.
> Adds round id to ban details

- public_log_parser.php
preps for the sql logging changes in https://github.com/tgstation/tgstation/pull/30207
> sql log changes

- public_log_parser.php
What it says on the tin.
@MrStonedOne
> Adds crew manifest file to public logs

- public_log_parser.php
> Adds support for the round end data json file.

- public_log_parser.php
Required for https://github.com/tgstation/tgstation/pull/38742 as per @Jordie0608
> Adds support for circuit log parsing

- tgdb/include/include.php
Since this was made before we changed to using unsigned ints for ip columns.
From @carbonhell
> Convert ip to int for auth_ip

- public_log_parser.php
> Adds job debug log to log parser.

- tgdb/include/include.php
- tgdb/irvpolltally.php
- tgdb/playerdetails.php
So it can be later be removed altogether.
I don't know php to know if this is valid code but this is mostly copy-paste-edited so it's probably fine.
Not too sure about the RIGHT JOIN, I'll have to test it out when I get home.
> Tries to replace lastadminrank

- public_log_parser.php
> Add telecomms.log to log parser

- tgdb/include/include.php
@Jordie0608 
people with prefixes couldn't use tgdb
> fix ip auth

- public_log_parser.php
For https://github.com/tgstation/tgstation/pull/42817
> Adds virus.log to parser

- public_log_parser.php
> Adds paintings to the parser.

- public_log_parser.php
> Exposes paintings.json in parsed logs

- index.html
We aint used phpBB3 for about 4 years, and we moved domain almost a year ago. Spotted this earlier so fixing it now.
> Updates link for paradise

- index.html
- tg.css
- tgdb/tg.css
Removes border-radius on the top corners of the site navbar
Moves site attribution into the container
> Corner case

- gamebanner.php
I plan on removing this from the world topic alongside the rest of mode related code.
> Remove references to gamemodes

- tg.css
Fix of jumping dropdown navbar menu on hover
> Fix of jumping dropdown navbar menu on hover

- public_log_parser.php
I forgot to do this when I added this logging.
> Adds speech_indicators.log to the public logs.

- public_log_parser.php
https://github.com/tgstation/tgstation/pull/70034
> adds signals log

- public_log_parser.php
No reason for it to be private
> Add death logging to public logs

- public_log_parser.php
Add silo.json to the parsed-logs which was added by https://github.com/tgstation/tgstation/pull/74806
> Add silo.json to parsed-logs
